name: Build Project

on:
  push:
    branches: [ Renewal_SDK, Renewal_SDK_dev ]
  pull_request:
    branches: [ Renewal_SDK, Renewal_SDK_dev ]
  workflow_dispatch:

jobs:
  build-sdk:
    name: Build SDK [${{ matrix.Configuration }}]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release, Debug]
        Platform: [x64]
    steps:
    - uses: actions/checkout@main

    - uses: microsoft/setup-msbuild@main

    - uses: nuget/setup-nuget@main

    - name: Restore NuGet packages
      run: nuget restore Source\Engine.sln

    - name: Build
      working-directory: Source
      env:
        CL: /DNIGHT_BUILD_NUMBER=${{ github.run_number }}
      run: msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" Engine.sln

    - name: Prepare artifacts
      shell: cmd
      run: utils/misc/xr_pack_build.cmd "${{ matrix.Configuration }}" "${{ matrix.Platform }}" "Build${{ github.run_number }}"

    - name: Upload HybridXRay artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: HybridXRay.*.7z

    - name: Upload Symbols
      uses: kittaakos/upload-artifact-as-is@v0
      if: matrix.Configuration == 'Release'
      with:
        path: Symbols.*.7z

    - name: Update latest-nightly tag
      uses: EndBug/latest-tag@latest
      if: github.ref_name == 'Renewal_SDK_dev'
      id: update-latest-nightly-tag
      with:
        ref: latest-nightly

  publish-sdk:
    needs: build-sdk
    name: Publish SDK
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@main
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts/

    - name: Publish latest nightly build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release delete latest-nightly --yes; gh release create latest-nightly (Get-ChildItem artifacts/*.7z -Recurse) --prerelease --title "Последняя ночная сборка/Latest nightly build" --notes "### Это последняя ночная сборка, скомпилированная из последнего коммита`n### This is the latest nightly build compiled from the latest commit"