name: Build Project

on:
  push:
    branches: [ Renewal_SDK, Renewal_SDK_dev ]
  pull_request:
    branches: [ Renewal_SDK, Renewal_SDK_dev ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }} (msvc)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release, Debug]
        Platform: [x64]
    steps:
    - uses: actions/checkout@main

    - uses: microsoft/setup-msbuild@main

    - uses: nuget/setup-nuget@main

    - name: Restore NuGet packages
      run: nuget restore Source\Engine.sln

    - name: Build
      working-directory: Source
      run: set CL=/DNIGHT_BUILD_NUMBER=${{ github.run_number }}; msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" Engine.sln

    - name: Prepare artifacts
      shell: cmd
      run: utils/misc/xr_pack_build.cmd "${{ matrix.Configuration }}" "${{ matrix.Platform }}" "Build${{ github.run_number }}"

    - name: Upload HybridXRay artifact
      uses: actions/upload-artifact@main
      with:
        name: HybridXRay.${{ matrix.Configuration }} ${{ matrix.Platform }} (github-${{ github.run_number }}).7z
        path: HybridXRay.*.7z

    - name: Upload Symbols
      uses: actions/upload-artifact@main
      if: matrix.Configuration == 'Release'
      with:
        name: Symbols.${{ matrix.Configuration }} ${{ matrix.Platform }} (github-${{ github.run_number }}).7z
        path: Symbols.*.7z

    - name: Update latest-nightly tag
      uses: EndBug/latest-tag@latest
      if: github.ref_name == 'Renewal_SDK_dev'
      id: update-latest-nightly-tag
      with:
        ref: latest-nightly

    - name: Publish latest nightly build
      if: ${{ steps.update-latest-nightly-tag.outcome == 'success' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release delete latest-nightly --yes; gh release create latest-nightly (get-item *.*.7z) --prerelease --title "Последняя ночная сборка/Latest nightly build" --notes "### Это последняя ночная сборка, скомпилированная из последнего коммита`n### This is the latest nightly build compiled from the latest commit"
